AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Py Spotty api'

Parameters:
  DEBUG:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  SpotifyClientId:
    Type: String
    Default: '{{resolve:ssm:JafSpotifyClientId:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafSpotifyClientId:1}}'
  SpotifyClientSecret:
    Type: String
    Default: '{{resolve:ssm:JafSpotifySecret:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafSpotifySecret:1}}'

Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Runtime: python3.9
    Environment:
      Variables:
        DEBUG: !Ref DEBUG
        SpotifyClientId: !Ref SpotifyClientId
        SpotifyClientSecret: !Ref SpotifyClientSecret

Resources:
  HttpApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Domain:
        DomainName: py-adminquiz.jaf-unwrapped.com
        CertificateArn: arn:aws:acm:ap-southeast-2:355151872526:certificate/12c34da1-c039-4fc4-9636-05571fdb3df9
        Route53:
          HostedZoneId: Z05897963LYPVXX455E44

  CreateQuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: functions/create_quiz.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: SpotifyProfile
        - DynamoDBCrudPolicy:
            TableName: SpotifyQuiz
      Events:
        PostCreateQuiz:
          Type: Api
          Properties:
            Path: /quiz/{type}
            Method: post
            RestApiId: !Ref HttpApiGateway
            RequestParameters:
              - method.request.path.type:
                  Required: true
        OptionsCreateQuiz:
          Type: Api
          Properties:
            Path: /quiz/{type}
            Method: options
            RestApiId: !Ref HttpApiGateway
            RequestParameters:
              - method.request.path.type:
                  Required: true

Outputs:
  CreateQuizFunction:
    Description: Python quiz function
    Value: !Ref CreateQuizFunction
  HttpApiGateway:
    Description: Py Api Gateway
    Value: !Ref HttpApiGateway